### ISSUE TITLE
C-k and C-y no longer work 

### ISSUE THREAD

**Issue by onedigit** [tuttieee/vscode-emacs-mcx#260]
Many thanks for this excellent extension which I've been using for quite some time.

version: 0.19.1

C-k and C-y no longer appear to work after the update of 25-Apr-2020.  When I check the keybindings, they are there, but the keys don't actually work.

I had to go back to the "Emacs Friendly Keymap", 0.9.0 and disable this one, in order to get C-k and C-y working again.

**Comment by tuttieee** [comment]
Thank you for reporting!
Which OS are you using?

**Comment by tuttieee** [comment]
I confirmed that the error occurs on Windows.
I will fix it.

---

Development memo:
It's because of bundling (#257 ).
Clipboardy's executable has been omitted during bundling.

**Comment by tuttieee** [comment]
Fixed in 0.19.2

**Comment by onedigit** [comment]
Thanks for quickly looking into this.  Got 0.19.3, but the issue persists.  

OS: Fedora Linux 31
Kernel: 5.6.6-200.fc31.x86_64
